# Generated by Django 3.1.6 on 2023-09-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_auto_20230927_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
