# Generated by Django 3.1.6 on 2023-09-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_deal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
