# Generated by Django 3.1.6 on 2023-09-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0006_delete_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='img')),
                ('price', models.IntegerField()),
                ('info', models.TextField()),
                ('offer', models.BooleanField(default=False)),
                ('link', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
