# Generated by Django 3.1.6 on 2023-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0007_auto_20230927_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
